name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11  # You can specify the Java version you need

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test
