name: Build and Test

on:
  push:
    branches:
      - CSE464-2023-Sgomez47
  pull_request:
    branches:
      - CSE464-2023-Sgomez47

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Java cache
        run: |
          echo "Clearing Java cache"
          rm -rf $RUNNER_TOOL_CACHE/Java*
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: target/*.jar
